antfroger_travel_with_me_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: AntfrogerTravelWithMeBundle:Default:index, name: World }

antfroger_travel_with_me_show_user:
    pattern:  /user/{username}
    defaults: { _controller: AntfrogerTravelWithMeBundle:User:show}