#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

# Copy parameters.yml.dist
cd $OPENSHIFT_REPO_DIR/app/config
cp parameters.yml.dist parameters.yml

# Update the configuration of the parameters.yml file
sed -i '/database_host/d' parameters.yml
sed -i '/database_port/d' parameters.yml
sed -i '/database_user/d' parameters.yml
sed -i '/database_password/d' parameters.yml

# Update the web directory in composer.json
cd $OPENSHIFT_REPO_DIR/
sed 's/"symfony-web-dir": "web"/"symfony-web-dir": "php"/' composer.json