#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

# Copy parameters.yml.dist
echo 'Copy parameters'
cd $OPENSHIFT_REPO_DIR/app/config
cp parameters.yml.dist parameters.yml

# Update the web directory in composer.json
echo 'Update composer.json configuration'
cd $OPENSHIFT_REPO_DIR/
sed -i 's/"symfony-web-dir": "web"/"symfony-web-dir": "php"/' composer.json

echo 'Update vendors'
curl -sS https://getcomposer.org/installer | php
php composer.phar install --prefer-dist --optimize-autoloader

echo 'Clear cache'
php app/console cache:clear --env=prod --no-debug

echo 'Dump assets'
php app/console assetic:dump --env=prod --no-debug

# Update the configuration of the parameters.yml file
echo 'Update parameters.yml configuration'
sed -i '/database_host/d' parameters.yml
sed -i '/database_port/d' parameters.yml
sed -i '/database_user/d' parameters.yml
sed -i '/database_password/d' parameters.yml