imports:
    - { resource: config.yml }
    - { resource: "@TWMSiteBundle/Resources/config/config_dev.yml" }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

h4cc_alice_fixtures:
    object_manager: doctrine.orm.entity_manager
    locale: %locale%

monolog:
    handlers:
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
        firephp:
            type:  firephp
            level: info
        chromephp:
            type:  chromephp
            level: info

#swiftmailer:
#    delivery_address: me@example.com
