security:
    encoders:
        Antfroger\DemoBundle\Entity\User:
          algorithm: sha512
          iterations: 6100

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: { class: AntfrogerDemoBundle:User }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/twm/demo/secured/login$
            security: false

        secured_area:
            pattern:    ^/twm/demo/secured/
            form_login:
                check_path: _twm_security_check
                login_path: _twm_demo_login
                default_target_path: antfroger_demo_homepage
            logout:
                path:   _twm_demo_logout
                target: antfroger_demo_homepage
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/twm/demo/secured/hello/admin/, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
