parameters:
#    twm_demo.example.class: TWM\DemoBundle\Example

services:
#    twm_demo.example:
#        class: %twm_demo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
