parameters:
#    antfroger_demo.example.class: Antfroger\DemoBundle\Example

services:
#    antfroger_demo.example:
#        class: %antfroger_demo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
