bazinga_faker:
    orm: doctrine
    locale: "%locale%"
    entities:
        TWM\SiteBundle\Entity\Travel\Travel\Travel:
            number: 1
            custom_formatters:
              name: { method: sentence, parameters: [ 3 ] }
              startedAt: { method: null }
              finishedAt: { method: null }
              duration: { method: null }